const languageCodes = {
    afr: 'Afrikaans',
    ara: 'Arabic',
    aze: 'Azerbaijani',
    bel: 'Belarusian',
    bos: 'Bosnian',
    bul: 'Bulgarian',
    cat: 'Catalan; Valencian',
    ces: 'Czech',
    chi_sim: 'Chinese - Simplified',
    chi_tra: 'Chinese - Traditional',
    cym: 'Welsh',
    dan: 'Danish',
    deu: 'German',
    ell: 'Greek, Modern (1453-)',
    eng: 'English',
    est: 'Estonian',
    eus: 'Basque',
    fas: 'Persian',
    fin: 'Finnish',
    fra: 'French',
    gle: 'Irish',
    glg: 'Galician',
    grc: 'Greek, Ancient (-1453)',
    hat: 'Haitian; Haitian Creole',
    hin: 'Hindi',
    hrv: 'Croatian',
    hun: 'Hungarian',
    ind: 'Indonesian',
    isl: 'Icelandic',
    ita: 'Italian',
    jpn: 'Japanese',
    kan: 'Kannada',
    kat: 'Georgian',
    kaz: 'Kazakh',
    kir: 'Kirghiz; Kyrgyz',
    kor: 'Korean',
    kur: 'Kurdish',
    lat: 'Latin',
    lav: 'Latvian',
    lit: 'Lithuanian',
    mkd: 'Macedonian',
    mlt: 'Maltese',
    msa: 'Malay',
    nep: 'Nepali',
    nld: 'Dutch; Flemish',
    nor: 'Norwegian',
    pol: 'Polish',
    por: 'Portuguese',
    ron: 'Romanian',
    rus: 'Russian',
    slk: 'Slovak',
    slv: 'Slovenian',
    spa: 'Spanish; Castilian',
    sqi: 'Albanian',
    srp: 'Serbian',
    srp_latn: 'Serbian - Latin',
    swa: 'Swahili',
    swe: 'Swedish',
    syr: 'Syriac',
    tha: 'Thai',
    tur: 'Turkish',
    uig: 'Uyghur',
    ukr: 'Ukrainian',
    urd: 'Urdu',
    uzb: 'Uzbek',
    vie: 'Vietnamese',
  };
export default languageCodes;